### ISSUE TITLE
DSE Consistency Check Hangs in VMs

### ISSUE THREAD

**Issue by bubbagump210** [opendedup/sdfs#11]
I am using CentOS 7 VMs to test SDFS. It seems that regardless of the hypervisor (I tried Virtual Box and Parallels) the DSE Consistency Check hangs at 0% and never completes. I cannot reproduce this on physical hardware. As for methodology, I was simply testing the time to run a DSE Consistency Check. I have ~1GB in the chunk store, so it is a relatively small amount of data. I unmounted the SDFS volume gracefully, edited the XML to change `closed-gracefully` to `false` to force a DSE check. The logs provide no useful information other than the mention of the DSE check starting. Let me know what other information I can provide.

**Comment by opendedup** [comment]
check for a .lock file in /opt/sdfs/volumes/<volume-name>/chunkstore/hdb .
If its there, remove it.

**Comment by bubbagump210** [comment]
Negative, the .lock file does not exist.

```
[root@localhost ~]# cd /sdfs/repo1/chunkstore/hdb/
[root@localhost hdb]# ls -a | grep -i lock
[root@localhost hdb]# cat /etc/sdfs/repo1-volume-cfg.xml | grep grace
<volume allow-external-links="true" capacity="10 GB" closed-gracefully="false" cluster-block-copies="2" cluster-id="sdfs-cluster" cluster-rack-aware="false" cluster-response-timeout="256000" current-size="0" dse-comp-size="0" dse-size="0" duplicate-bytes="0" maximum-percentage-full="0.95" name="repo1" path="/sdfs/repo1/files" perf-mon-file="/opt/sdfs//logs/volume-repo1-perf.json" read-bytes="0.0" read-timeout-seconds="-1" serial-number="434071304" sync-files="false" use-dse-capacity="true" use-dse-size="true" use-perf-mon="false" volume-clustered="false" write-bytes="0" write-timeout-seconds="-1"/></subsystem-config>
[root@localhost hdb]# mount /repodata/
/sbin/mount.sdfs: line 2: modprobe: command not found
[root@localhost hdb]# Running Program SDFS Version 3.1.9
reading config file = /etc/sdfs/repo1-volume-cfg.xml
Loading Existing Hash Tables |))))))))))))))))))))))))))))))))))))))))))))))))))| 100% 

ReCreating BloomFilters |))))))))))))))))))))))))))))))))))))))))))))))))))| 100% 

ReCreating BloomFilters |))))))))))))))))))))))))))))))))))))))))))))))))))| 100% 

Waiting for all BloomFilters creation threads to finish done
Loaded entries 817944
Running Consistancy Check on DSE, this may take a while
Scanning DSE |]                                                 | 0% 
```

And it then sits in this state indefinitely and there is no log output.

**Comment by opendedup** [comment]
can you please send along the log files from /var/log/sdfs for review?

**Comment by bubbagump210** [comment]
See attached. Let me know if I can provide anything further. Thanks!

[SDFSlogs.tar.zip](https://github.com/opendedup/sdfs/files/315305/SDFSlogs.tar.zip)

**Comment by opendedup** [comment]
From the logs it looks like either there is a .lock file at
/sdfs/repo1/chunkstore/hdb/.lock or  closed-gracefully="false". Can you
verify?

**Comment by bubbagump210** [comment]
closed-gracefully="false" is the current state.

**Comment by opendedup** [comment]
How about the .lock file ?

how about the .lock file at /sdfs/repo1/chunkstore/hdb/

run  ls -lah /sdfs/repo1/chunkstore/hdb/

**Comment by bubbagump210** [comment]
There is no lock file. 

![screen shot 2016-06-15 at 10 27 10 am](https://cloud.githubusercontent.com/assets/19892745/16083642/bffdcd26-32e3-11e6-8ccd-9d858407cb1c.png)

**Comment by bubbagump210** [comment]
I just tried the 3.2.0 beta and this seems to be fixed now. Hopefully that was intentional. :)
