### ISSUE TITLE
build failure

### ISSUE THREAD

**Issue by richman1000000** [opendedup/sdfs#112]
I'm trying to build deb package. during compilation there is error happening 
See screenshots below
![image](https://user-images.githubusercontent.com/9943374/102995050-48addd00-4531-11eb-9170-4e42423b6c3b.png)
![image](https://user-images.githubusercontent.com/9943374/102995217-9de9ee80-4531-11eb-8049-9080372ede8c.png)

**Comment by richman1000000** [comment]
#118  3.12 version build failure 

![image](https://user-images.githubusercontent.com/9943374/115232945-f451ed00-a11f-11eb-953e-6966a5ae686f.png)

**Comment by opendedup** [comment]
What branch are you using? 3.11?

**Comment by richman1000000** [comment]
3.12. latest.
also I tried to build from master but it fails with same error

**Comment by richman1000000** [comment]
found solution.
