### ISSUE TITLE
Same IV spec is used for every file upload in a single volume which is insecure.

### ISSUE THREAD

**Issue by DeepaSharma1** [opendedup/sdfs#13]
Setup Configuration :-
OS - Ubuntu ( Kernel Version 3.13.0-32)
RAM - 8GB
SDFS Version - Latest Code taken from GIT Hub with Master Branch and compiled
Following scenario has been seen in the sdfs code :-
1.  In sdfs/src/org/opendedup/util/EncryptUtils.java file, the IV (Initialization Vector) can be read in either of the below ways :-

a.  By passing “encryption-iv” parameter while creating the volume using mkfs.sdfs command or
b.  If not passed with “encryption-iv” parameter then it is read from sdfs/src/org/opendedup/sdfs/Main.java file

Which is further passed as an argument in IvParameterSpec as 

IvParameterSpec spec = new IvParameterSpec(iv);
1.  The object of IvParameterSpec is then passed in cipher.init() method as 

a.  in encryptCBC() method :-
cipher.init(Cipher.ENCRYPT_MODE, key, spec);

b.  decryptCBC() method :-
cipher.init(Cipher.DECRYPT_MODE, key, spec);

Test Scenario :-
1.  Create the volume.
2.  Copy/upload a file to the volume.
3.  Download the file from the volume.

Expected Result :-

The IV “spec” used must be different for each file upload in the volume.

Current Result :-

As I have put the logs to print the spec while upload(encrypt) and download(decrypt), so, its noted that the same spec is used for each file upload in the same volume which is insecure.

So, is there any way to make use of different IV for different file upload in the same volume.

Thanks,
Deepa

**Comment by opendedup** [comment]
This is possible - I would add an IV spec parameter to the metadata on each
object.

**Comment by DeepaSharma1** [comment]
Can you please suggest at which place in the SDFS code you are trying to add the IV Spec ?

**Comment by opendedup** [comment]
I would recommend adding an attribute to the package
org.opendedup.sdfs.filestore.cloud.Batch.*BatchAwsS3ChunkStore in the
writehashblobarchive interface. I would then add update
*org.opendedup.util.*EncryptUtils
and update encryptCBC and decryptCBC with an iv parameter.*

**Comment by DeepaSharma1** [comment]
The writeHashBlobArchive() interface is used by all the cloud Chunk Store files like BatchGSChunkStore.java, BatchAzureChunkStore.java and BatchAwsS3ChunkStore.java. But, it is not being used by the local SDFS volume.
So, please suggest in case of local volume, where we need to add the IV in SDFS code.

**Comment by opendedup** [comment]
This is a good point. I think updating the HashBlobArchive is a better
interface since that is where the data is encrypted and decrypted. The IV
could be added to the head of the file or each segment.

**Comment by opendedup** [comment]
Fixed

**Comment by DeepaSharma1** [comment]
Hi Sam,

With the latest code fix also, it is found that the ivspec used for each file upload in a single volume is same. Is there any flag which has to be set to enable IV generation per chunk ?

**Comment by opendedup** [comment]
The ivspec metadata has only been implemented in the BatchAwsS3ChunkStore
at the moment. It adds an "ivspec" metadata element to the uploaded files
and keys. For chunks the ivspec is prepended to the chunk itself. For files
take a look at the following snippet from BatchAwsS3ChunkStore and you will
see the ivspec changes per file.

byte [] ivb = null;
if (Main.chunkStoreEncryptionEnabled) {
try {
ivb = PassPhrase.getByteIV();
EncryptUtils.encryptFile(p, e,new IvParameterSpec(ivb));
} catch (Exception e1) {
throw new IOException(e1);
}
p.delete();
p = e;
}
String objName = pth;
ObjectMetadata md = new ObjectMetadata();
Map<String, String> umd = FileUtils.getFileMetaData(f,
Main.chunkStoreEncryptionEnabled);
md.setUserMetadata(umd);
md.addUserMetadata("lz4compress",
Boolean.toString(Main.compress));
md.addUserMetadata("encrypt",
Boolean.toString(Main.chunkStoreEncryptionEnabled));
if(ivb != null)
md.addUserMetadata("ivspec", BaseEncoding.base64().encode(ivb));

**Comment by DeepaSharma1** [comment]
Hi Sam,

To encrypt every chunk with different IV for local SDFS volume, I am trying the following approach :-

1.	I have randomly generated the IV i.e. ivb in putChunk() method of HashBlobArchive.java file and sent the IV with the chunk in encryptCBC() method of EncryptUtils.java file i.e. 

chunk = EncryptUtils.encryptCBC(bf.array(),ivb);

2.	In EncryptUtils.java, 

•	In encryptCBC() method i.e. encryptCBC(byte[] chunk, byte[] iv) , below 3 steps have been followed :-

a.	The “ivspec” will be generated using the IV passed in step 1 and will be used to generate the ciphertext.
b.	The iv will be prepended with the ciphertext in a new combined byte array
c.	This new combined byte array will be returned.

•	In decryptCBC() method i.e. decryptCBC(byte[] encChunk) , below step has been followed :-

a.	Since the encChunk is the combined array of IV and Ciphertext so, the first 16 bytes read is “IV” and the rest is “Ciphertext” 

Is this approach fine to proceed with ? However, I am pretty much closer with the coding of this implementation.

**Comment by opendedup** [comment]
I think this is the way I coded it two weeks ago. Have you seen the latest
trunk? Please let me know if I missed something

**Comment by DeepaSharma1** [comment]
Yes, I have seen the changes but with that also, the file upload was taking the same IV each time.

**Comment by opendedup** [comment]
OK - Thanks!

**Comment by DeepaSharma1** [comment]
Hi Sam,

We want to add the support for "multiple encryption-types" in SDFS code.
 
For this, we need to store the encryption-type(used at the time of encryption) in Metadata, so that while remounting , the same encryption-type can be used for decryption in case of cloud file upload/download.

So, please suggest how can the encryption-type be stored in the following :-

1.	In Local SDFS Copy:-
 
As there is no Metadata present.

2.	In Cloud Copy :-

The Metadata is present to store the information for cloud file copy but is there need to store the encryption-type in each Cloud file ?
Is there any generic code written in SDFS to store the encryption-type in Metadata so that all the cloud files can use the same code ?

**Comment by opendedup** [comment]
I think you should start off by creating a generic Encryption interface
class that any class can use for encryt/decrypt. Any encryption algo would
have its own call that would implement the interface.

something line the following method signatures:

byte [] encrypt(byte [] data, byte [] key); //returns iv or other metadata
at byte array
byte [] decrypt(byte [] encdata,byte[] key,byte [] metadata) //returns the
decrypted metadata

the metadata can then be prepended to each chunk or added at metadata to an
object. does that make sense?

**Comment by DeepaSharma1** [comment]
Hi,

Thanks.
But, still the question persists for local SDFS copy as we do not have Metadata for local SDFS file copy.

So, how and where can we store the “encryption-type” for LOCAL SDFS file copy so that the same encryption-type can be used while decryption ?

**Comment by opendedup** [comment]
For local sdfs copy the metadata should be stuffed in the HashBlobArchive
similar to how it's done today for the iv.

I am not quite sure how it should be done for the file metadata but will
take any suggestions you might have.

**Comment by DeepaSharma1** [comment]
The copy operation for AWS Cloud volume is getting failed for the sdfs code(Committed on 29-Aug-2016). 
We updated some proxy related changes and after that created AWS Volume. We are able to mount the volume but not able to perform copy operation(copy a file to AWS Volume).

No issue is seen with local & Google Volume.

However, the Amazon account was being created with the SDFS code of 2nd Aug 2016 with the proxy settings. And no issue is seen with copy operation.

So can you suggest what other changes are required.

**Comment by opendedup** [comment]
Are you using the latest libraries from the jar directory? I did update the
aws-sdk to the latest version with the latest release. So you are trying to
test through an http proxy server?

**Comment by DeepaSharma1** [comment]
Yes, we are using the latest jar files.
Sam, is there any generic way to set the PROXY using command line options at the time of creating cloud bucket itself rather than setting in each cloud file ?

**Comment by opendedup** [comment]
Not currently. I will add it for the next release.

The proxy setting should be added to the "connection-props" tag in the xml.

Below are the available obtions.
proxy-host
proxy-domain
proxy-password
proxy-port
proxy-username
