### ISSUE TITLE
The Windows download on the Opendedup website is `404 NOT FOUND`

### ISSUE THREAD

**Issue by rautamiekka** [opendedup/sdfs#143]
The link `http://www.opendedup.org/downloads/sdfs-latest.exe` at `https://opendedup.org/odd/download/` returns `404 NOT FOUND`.

**Comment by Stannieman** [comment]
Yep this is a problem for me too. I have an old volume from which I'd like to recover data.

**Comment by dillfrescott** [comment]
You can still get the latest version from wayback machine.

`https://web.archive.org/web/20220425055614/http://www.opendedup.org/downloads/sdfs-latest.exe`

Someone needs to tell them to fix the link though!

**Comment by dillfrescott** [comment]
I dont think this is necessarily completed since the actual link still gives a 404...

**Comment by rautamiekka** [comment]
Yeah that absolutely doesn't fly.
