### ISSUE TITLE
typo "--volume_name" in Admin guide

### ISSUE THREAD

**Issue by tony-travis** [opendedup/sdfs#17]
There is a typo in the "Admin guide for Version 2.0":
[administration-guide](http://www.opendedup.org/sdfs-20-administration-guide)

> Creating A Standalone SDFS Volume
> 
> A simple standalone volume named "dedup" with a dedup capacity of 1TB and a block size of 128K > > run the following command:
> 
> mkfs.sdfs --volume_name=dedup --volume-capacity=1TB
> [...]

This should be --volume-name for sdfs version 3.3.6

`
mkfs.sdfs --volume_name dedup --volume-capacity 1TB
Attempting to create SDFS volume ...
ERROR : Unable to create volume because org.apache.commons.cli.UnrecognizedOptionException: Unrecognized option: --volume_name
org.apache.commons.cli.UnrecognizedOptionException: Unrecognized option: --volume_name
	at org.apache.commons.cli.Parser.processOption(Parser.java:363)
	at org.apache.commons.cli.Parser.parse(Parser.java:199)
	at org.apache.commons.cli.Parser.parse(Parser.java:85)
	at org.opendedup.sdfs.VolumeConfigWriter.parseCmdLine(VolumeConfigWriter.java:145)
	at org.opendedup.sdfs.VolumeConfigWriter.main(VolumeConfigWriter.java:1204)

mkfs.sdfs --volume-name=dedup --volume-capacity=1TB
Attempting to create SDFS volume ...
Volume [dedup] created with a capacity of [1TB]
check [/etc/sdfs/dedup-volume-cfg.xml] for configuration details if you need to change anything
`

**Comment by opendedup** [comment]
Fixed!
