### ISSUE TITLE
sdfscli volume info

### ISSUE THREAD

**Issue by crcro** [opendedup/sdfs#24]
is there any way to display multiple volumes statistics (sdfscli --volume-info).
i've created a default one in /opt and another volume (pool) in /backup but there is no parameter for --volume-info and it always displays the default /opt volume info

**Comment by opendedup** [comment]
There is no way to do this today.

To see the other volume's stats run sdfscli --volume-info --port 6443

**Comment by crcro** [comment]
i've tried that but i thing that what is returned is not usefull because it does not reflect the reality:

- i have only 1 file (and 2 dir) on that volume
- df reports only 31Mb storage used

but sdfscli --volume-info --port 6443 returns:

Files : 50
Volume Capacity : 490 GB
Volume Current Logical Size : 48.59 GB
Volume Max Percentage Full : 95.0%
Volume Duplicate Data Written : 16.73 GB
Unique Blocks Stored: 35.83 MB
Unique Blocks Stored after Compression : 30.7 MB
Cluster Block Copies : 2
Volume Virtual Dedup Rate (Unique Blocks Stored/Current Size) : 99.93%
Volume Actual Storage Savings (Compressed Unique Blocks Stored/Current Size) : 99.94%
Compression Rate: 14.33%
