### ISSUE TITLE
Project still alive?

### ISSUE THREAD

**Issue by nova-2nd** [opendedup/sdfs#25]
Hi all,

Is this project still alive?
Missing a lot of proper documentation. No communication in the forum, email
Seems like this project is moving into a commercial direction (Datish Systems) with their virtual appliance which already asks for a license.

Greets,
Stefan Nader

**Comment by tony-travis** [comment]
On 09/06/17 11:37, nova-2nd wrote:
> Hi all,
> 
> Is this project still alive?
> Missing a lot of proper documentation. No communication in the forum, email
> Seems like this project is moving into a commercial direction (Datish
> Systems) with their virtual appliance which already asks for a license.

Hi, Stefan.

I think SDFS looks very interesting, but I dropped it like a hot brick
when I discovered a BUG that overwrites the _source_ files on an SDFS
filesystem when using "rsync". This was a complete show-stopper for me
and I've seen no evidence yet that the BUG has or will be fixed - Pity.

Bye,

  Tony.

-- 
Minke Informatics Limited, Registered in Scotland - Company No. SC419028
Registered Office: 3 Donview, Bridge of Alford, AB33 8QJ, Scotland (UK)
tel. +44(0)19755 63548                    http://minke-informatics.co.uk
mob. +44(0)7985 078324        mailto:tony.travis@minke-informatics.co.uk

**Comment by opendedup** [comment]
The project is very active. We are working on many aspects of the solution
right now including support of backup targets such as netbackup and backup
exec.

The project has corporate sponsorship and we are bringing up more resources
to address questions.

I apologize for the lack of follow up here but have been heads down with
this integration project. If there are specific features or fixes you
require please post to the forum and I will work on adding them.

**Comment by tony-travis** [comment]
On 09/06/17 15:34, Sam Silverberg wrote:
> The project is very active. We are working on many aspects of the solution
> right now including support of backup targets such as netbackup and backup
> exec.
> 
> The project has corporate sponsorship and we are bringing up more resources
> to address questions.
> 
> I apologize for the lack of follow up here but have been heads down with
> this integration project. If there are specific features or fixes you
> require please post to the forum and I will work on adding them.

Hi, Sam.

I already reported the BUG...

The _source_ files on an ext4 FS are overwritten when using "rsync" to
backup onto an SDFS filesystem. Fortunately, my disaster recovery system
worked and I didn't lose any files. It's made me cautious about using
SDFS, but I'm still very interested in trying it out again when you've
identified the BUG and fixed it. I think SDFS could be very useful.

Thanks,

  Tony.

-- 
Minke Informatics Limited, Registered in Scotland - Company No. SC419028
Registered Office: 3 Donview, Bridge of Alford, AB33 8QJ, Scotland (UK)
tel. +44(0)19755 63548                    http://minke-informatics.co.uk
mob. +44(0)7985 078324        mailto:tony.travis@minke-informatics.co.uk

**Comment by opendedup** [comment]
Thanks Tony- I though I had fixed this a while ago but will revisit in this
release 3.4.3
