### ISSUE TITLE
3.5.2 java errors during mount - Windows 2012 R2

### ISSUE THREAD

**Issue by NickThrew** [opendedup/sdfs#42]
Version I downloaded shows 3.5.2 and I am unable to find a change log (or a commit) that I can find. We end up with java error (see next comment) when trying to mount a newly created volume/bucket pair. 

Short Term:
Wondering if there is a repo somewhere of previous compiled builds? I started working with this project just last week and I have a feeling I was using (and getting better success with) a previous version. 

Long Term:

- Fix / understand / workaround current mount errors (see comment below)
- Understand how to remount a volume where all we have is the data in a cloud bucket (DR event testing)
- Understand better which setting needs to be toggled to write in-line duplicated data to a cloud bucket that also is encrypted with a unique key of our choosing.

**Comment by NickThrew** [comment]
errors after clean install of 3.5.2 (with reboots) on up-to-date Windows 2012 R2 64-bit:

Volume creation (works):

> D:\Program Files\sdfs>mksdfs --sdfscli-disable-ssl --volume-name=google_bucket_s --volume-capacity=20TB --google-enabled true --cloud-access-key ************ --cloud-secret-key ************** --cloud-bucket-name opendedup-bucket-s --sdfscli-require-auth --sdfscli-password ************ --encrypt-config
Attempting to create SDFS volume ...
Encrypting Configuration
Volume [google_bucket_s] created with a capacity of [20TB]
check [D:\Program Files\sdfs\etc\google_bucket_s-volume-cfg.xml] for configuration details if you need to change anything

Volume mount (does not complete/hangs):

> D:\Program Files\sdfs>mountsdfs.exe -v google_bucket_s -m S -e *******************
Running Program SDFS Version 3.5.2
reading config file = D:\Program Files\sdfs\etc\google_bucket_s-volume-cfg.xml
Exception in thread "main" java.lang.UnsatisfiedLinkError: C:\Users\me\AppData\Local\Temp\librocksdbjni1742562294649878028.dll: A dynamic link library (DLL) initialization
routine failed
        at java.lang.ClassLoader$NativeLibrary.load(Native Method)
        at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1941)
        at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1824)
        at java.lang.Runtime.load0(Runtime.java:809)
        at java.lang.System.load(System.java:1086)
        at org.rocksdb.NativeLibraryLoader.loadLibraryFromJar(NativeLibraryLoader.java:78)
        at org.rocksdb.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:56)
        at org.rocksdb.RocksDB.loadLibrary(RocksDB.java:64)
        at org.rocksdb.RocksDB.<clinit>(RocksDB.java:35)
        at org.opendedup.collections.RocksDBMap.<clinit>(RocksDBMap.java:83)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:264)
        at org.opendedup.sdfs.filestore.HashStore.connectDB(HashStore.java:174)
        at org.opendedup.sdfs.filestore.HashStore.<init>(HashStore.java:83)
        at org.opendedup.sdfs.servers.HashChunkService.<init>(HashChunkService.java:79)
        at org.opendedup.sdfs.servers.HCServiceProxy.init(HCServiceProxy.java:202)
        at org.opendedup.sdfs.servers.SDFSService.start(SDFSService.java:78)
        at org.opendedup.sdfs.windows.fs.MountSDFS.main(MountSDFS.java:176)

And the command prompt just hangs needing a break-point.


There is still one final step since I will be using this platform in conjunction with Backup Exec 16 FP2 and that is to write the OST config - but that should not be a prereq of the above working without issue.

I was successful doing this on the same machine last week. Due to the way I test I wanted to see, this week, what a full rip and replace would work so I downloaded whatever the sdfs-latest.exe was last week and went through the Veritas w/ OpenDedup write-up and all worked without issue. Now I am unable to even mount a brand new volume on a brand new Google Cloud bucket I created and the only thing I can think of was the sdfs-latest.exe I used last week was a different version and the current version is breaking for me for some reason. Maybe there is more cleanup I need to do on the system beyond a full uninstall of both Dokan lib and SDFS 3.5.2?

Finally I am not clear on how one will "re"mount an "orphaned" volume when all you have is the Google bucket - think DR event. 

I was half way through this DR test when I started receiving these mount errors (above):

1. Install SDFS/Doken lib
2. Restart
3. Create, mount, and encrypt (config files) 20TB volume connected to a Google Cloud storage bucket
4. Configure new Backup Exec storage via OST with password to decrypt config
5. Write data (backups) to storage from Backup Exec jobs
6. Use gsutil to confirm appearance of deduplication (after writing the same data multiple times)
7. Delete the storage from Backup Exec
8. Uninstall both SDFS and Dokan lib
9. Restart
10. Download/install latest SDFS/Doken lib
11. Restart
12. ?? <-- Try to figure out the proper method on how I should "re"mount this volume Figuring that I would, at least, have to remember the original password (but maybe not as it was unclear to me if this password is used to encrypt the data at rest at Google or just encrypt the xml config files that were stored locally)
13. **Not attempted yet** _"re"mount the original storage that would have been mounted in Step 12 (if I knew how to do it) in BackupExec via OST_
14. **Not attempted yet** _Inventory & Catalog the "re"mounted storage and confirmed that function_
15. **Not attempted yet** _Attempt a restore from one of the Backup Exec sets from original storage_
16. **Not attempted yet** _Research a bit more on how the data encryption works for OpenDedup to confirm I can have the data encrypted in the Google bucket with a **unique** encryption key we create while still confirming In-line deduplication is not impacted_

So I am basically at a place where I am having issues mounting a brand new volume/bucket pair and I need to find more information/best practice on how to recover in case the server crashes or there is a DR event. 

Thanks

**Comment by egn1** [comment]
Hi,

I have the same problem on Windows 10 1703 with a fresh install. I can create the volume, but when I do  the mount I get the same exception. 

I used the commands provide in the Windows Quick Guide.

Thanks

**Comment by egn1** [comment]
I looked int the dll with dependency walker and it looks like a problem I just had this week with another library. 

Can it be that librocks dll is compiled with debug?

If yes, it may not run when loaded by a non debug program.
