### ISSUE TITLE
Can I configure opendedup not to use chunk comparison & lower memory

### ISSUE THREAD

**Issue by angsuman** [opendedup/sdfs#52]
Can I configure opendedup not to use chunk comparison (neither static nor dynamic)?
Can I safely reduce xms & xms to reduce memory requirement without adverse effect or should I change elsewhere too? 8GB is too high limit for my system. I am also thinking of running it on Raspberry Pi.

**Comment by skulkar2** [comment]
With what version are we trying this ? What's the value of max_open_files in the xml ? Calculation is like this :
In 3.5* version calculation is like this,

Memory required = 2000 + (max-open-files * max-file-write-buffers * 2)

You coud try reducing the max-open-files if there are not going to be more number of streams.

**Comment by angsuman** [comment]
Latest version.
Let me try it tomorrow and get back to you.
