### ISSUE TITLE
Cannot allocate memory: Native memory allocation (mmap) failed to map 88013275136 bytes for committing reserved memory

### ISSUE THREAD

**Issue by binary64** [opendedup/sdfs#53]
```
# mount.sdfs pool0 /media/pool0/
OpenJDK 64-Bit Server VM warning: INFO: os::commit_memory(0x00007f3fcc000000, 88013275136, 0) failed; error='Cannot allocate memory' (errno=12)
#
# There is insufficient memory for the Java Runtime Environment to continue.
# Native memory allocation (mmap) failed to map 88013275136 bytes for committing reserved memory.
# An error report file with more information is saved as:
# //hs_err_pid803.log
```

88 GB o_O :D

**Comment by binary64** [comment]
```
#  Out of Memory Error (os_linux.cpp:2627), pid=803, tid=140088930363136
#
# JRE version:  (8.0_72-b15) (build )
# Java VM: OpenJDK 64-Bit Server VM (25.72-b15 mixed mode linux-amd64 )
```

**Comment by skulkar2** [comment]
With what version are we trying this ? What's the value of max_open_files in the xml ? Calculation is like this : 
In 3.5* version calculation is like this,

`Memory required  = 2000 + (max-open-files * max-file-write-buffers * 2)`

You coud try reducing the max-open-files if there are not going to be more number of streams.

**Comment by binary64** [comment]
Ahh i see. My config is 

```
sysctl -w vm.max_map_count=262144
sysctl -w fs.file-max=1048576
```
and
```
* hard nofile 1048576
```

Version is sdfs-latest.deb installed today (sorry not at my desk atm)

**Comment by skulkar2** [comment]
Hi,

I meant the parameters in the configuration file which opendedup
I.e., /etc/sdfs/volname.xml

**Comment by inponomarev** [comment]
Got exactly the same message, with 88 Gb of memory. Just installed using instructions from http://opendedup.org/odd/linux-quickstart-guide/ on machine with 1Gb memory. max-open-files = 512, max-file-write-buffers=512

**Comment by richman1000000** [comment]
Hi!
I just got this error too
in file /usr/share/sdfs/mount.sdfs 
remove this  parameter
> -Xmx$MEMORY$MU

replace this one 
> -Xms$MEMORY$MU

 with 
> -Xms1M

**Comment by djrodgerspryor** [comment]
I too had this problem following the Debian quickstart guide with a 3TB volume (config had 512 max-open-files and 512 max-file-write-buffers).

It seems like the actual calculation in `/usr/share/sdfs/mount.sdfs` is:
```
Memory required = 2000 + (max-open-files * MIN(max-file-write-buffers, 80) * 2)
```

And the result is interpreted as *MB*, so the ~80GB number is exactly what I'd expect given that calculation. Is there something wrong in the number of max-file-write-buffers being put in the config by default? 512 seems high if the mount script is using 80 as a maximum.

I resolved the problem for now by dropping max-file-write-buffers to 8 and max-open-files to 256, but I don't really have a good idea of how that will effect performance.

**Comment by richman1000000** [comment]
yes, buut.
setting up **-Xmx**  - useless step, If you remove it - java less likely to hit out of memory error. You need to install zabbix or something else to monitor memory consumption.
setting up  -Xms1M - will cause java to consume less memory on start, which i think is nice.

currently I have 2 de-duplication volumes and only 2 GB of memory is busy out of 8 GBs.
by the way, my  **max-open-files=6000000** and **max-file-write-buffers=4096**

My question is - you not likely to hit 6000000 opened files  so why do you set those limits??

**Comment by Cat5TV** [comment]
I'm also experiencing this having followed the same guide as @inponomarev -- does anyone know what needs to change in that guide to make it work? I'd rather not start editing the sdfs source code - unless that's what's required. It must be a setting or something? Thanks! Glad I'm not alone.  :)

**Comment by richman1000000** [comment]
I ended up using this config parameters

> memtouse=`awk '/^Mem/ {printf($2);}' <(free --mega)`

and start parameter
> -Xms$memtouse$MU 

cause I have fully dedicated one machine (8 Core, 6 GB RAM ) to duplication, so I want sdfs to utilize whole memory without bothering of calculation.

PS .  **-Xmx**  is removed
