### ISSUE TITLE
lack of integrity check commands

### ISSUE THREAD

**Issue by richman1000000** [opendedup/sdfs#63]
If one of chunks broken, then de-duplicated data can be corrupted. We need to run hash check of stored chunks.
I there any way to run such check?

**Comment by richman1000000** [comment]
Now this have become issue!
I've been making backups of system on opendedup based storage.
And after curtain day all next backups became corrupted and unreadable .

**Comment by opendedup** [comment]
can you share the logs from your system?

**Comment by richman1000000** [comment]
I found out reason of this failure - power outage.
But integrity check of DDB and chunks  is still needed.

Log file do not contains errors other than error of outage.
But now during backups there is error when new version of corrupted file is transferred through NFS or SAMBA "IO error" or "Unspecified error" on source of file.
My solution at the moment was - create new sdfs and move data into it. The corrupted file is copied FROM storage successfully  event though it contains invalid data. But on new storage new versions of file is correct.

**Comment by richman1000000** [comment]
![image](https://user-images.githubusercontent.com/9943374/36295237-64519a2a-1310-11e8-97af-35dcf92a37a4.png)
one of program packages not working from deduplicated storage. checksum is different.
I do not want to rebuild storage. Can we somehow identified wrong hash of chunk in DDB and correct it?

**Comment by richman1000000** [comment]
this error is fixed in 3.5.8.5
