### ISSUE TITLE
error in new version of opendedup

### ISSUE THREAD

**Issue by richman1000000** [opendedup/sdfs#69]
hi!
today I've installed new version of opendedup, created new volume and got an error
sdfscli --port=6444 --cleanstore
This error is returned on any command. I've  downgraded back to 3.5 currently

![image](https://user-images.githubusercontent.com/9943374/37518174-429890e8-293e-11e8-80b8-e5311f8691b4.png)

**Comment by opendedup** [comment]
sdfscli --port=6444 --cleanstor  --password=admin should fix the issue. I
will fix this in the next release.

**Comment by richman1000000** [comment]
ok, working.
also problem with integrity is fixed in 3.5.8.5  #63
