### ISSUE TITLE
stuck when copy file(filesize is 4G+)

### ISSUE THREAD

**Issue by SamuelXu** [opendedup/sdfs#7]
On 2 CentOS 7 servers (ip77 and ip95); I created sdfs running SDFS source with a 400GB volume "poo0"  as same as http://www.opendedup.org/quickstart.
      When I put larger files on the sdfs volume (like CentOS img 4G+ ) the replication gets stuck when importing the Block data.

**Comment by opendedup** [comment]
Samuel,

Can you please send me your config setup? I am about to release 3.1.4 and
would like to see if this is a bug that needs to be fixed before release.

**Comment by SamuelXu** [comment]
[log_config.zip](https://github.com/opendedup/sdfs/files/211120/log_config.zip)

**Comment by SamuelXu** [comment]
I solved the problem by changing the file:
--- a/src/org/opendedup/sdfs/cluster/cmds/DirectWriteHashCmd.java
+++ b/src/org/opendedup/sdfs/cluster/cmds/DirectWriteHashCmd.java
@@ -146,17 +146,20 @@ public class DirectWriteHashCmd implements IOClientCmd {
 
                   };
                  ArrayList<PoolHC> ap = new ArrayList<PoolHC>();
+               {         
+                synchronized (soc) {
                    for (HashClientPool pool : pools) {
                        if (pool != null) {    
                            HashClient hc = (HashClient) pool.borrowObject();

                            hc.writeChunkAsync(this.hash, this.aContents, 0, this.aContents.length, l);
                            executor.execute(hc);      
                            PoolHC phc = new PoolHC(); 
                            phc.hc = hc;               
                            phc.pool = pool;           
                            ap.add(phc);               
                        }                      
                    }                  
+                }              
+            }          


here should be locked to avoid of deadlock in multithreads.

Is opendedup support one cluster replicate data from another? Thank you.

**Comment by opendedup** [comment]
Thanks for the update Samuel. I will review and incorporate the changes.
