### ISSUE TITLE
Missing sst files prevent opendedup disk from mounting

### ISSUE THREAD

**Issue by louisvd** [opendedup/sdfs#73]
My Fedora 27 PC froze (never happened before) and I had to hit the reset button.
It rebooted normally, and then I updated all the latest patches.  After a final reboot, it forced me to maintenance mode because the opendedup disk could not mount.  After removing it from fstab I could at least boot.

Trying to mount it manually, I get the following:

# mount -t sdfs pool0 /media/opendedup
Running Program SDFS Version 3.6.0.12 build date 2018-03-05 16:19
reading config file = /etc/sdfs/pool0-volume-cfg.xml
multiplier=32 size=8
mem=19668800 memperDB=2458600 bufferSize=1073741824 bufferSizePerDB=134217728
Loading Existing Hash Tables |))))))))))))))))))))))))))))))))))))))))))))]     | 88% java.io.IOException: org.rocksdb.RocksDBException: Can't access /000018.sst: IO error: while stat a file for size: /media/500GB-BKUP/sdfs-volumes/chunkstore/hdb-8708970613374839576/hashstore-sdfs/0/000018.sst: No such file or directory
Can't access /000012.sst: IO error: while stat a file for size: /media/500GB-BKUP/sdfs-volumes/chunkstore/hdb-8708970613374839576/hashstore-sdfs/0/000012.sst: No such file or directory
Can't access /000007.sst: IO error: while stat a file for size: /media/500GB-BKUP/sdfs-volumes/chunkstore/hdb-8708970613374839576/hashstore-sdfs/0/000007.sst: No such file or directory

	at org.opendedup.collections.RocksDBMap.init(RocksDBMap.java:301)
	at org.opendedup.sdfs.filestore.HashStore.connectDB(HashStore.java:187)
	at org.opendedup.sdfs.filestore.HashStore.<init>(HashStore.java:83)
	at org.opendedup.sdfs.servers.HashChunkService.<init>(HashChunkService.java:74)
	at org.opendedup.sdfs.servers.HCServiceProxy.init(HCServiceProxy.java:154)
	at org.opendedup.sdfs.servers.SDFSService.start(SDFSService.java:86)
	at fuse.SDFS.MountSDFS.setup(MountSDFS.java:214)
	at fuse.SDFS.MountSDFS.init(MountSDFS.java:253)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.commons.daemon.support.DaemonLoader.load(DaemonLoader.java:207)
Caused by: org.rocksdb.RocksDBException: Can't access /000018.sst: IO error: while stat a file for size: /media/500GB-BKUP/sdfs-volumes/chunkstore/hdb-8708970613374839576/hashstore-sdfs/0/000018.sst: No such file or directory
Can't access /000012.sst: IO error: while stat a file for size: /media/500GB-BKUP/sdfs-volumes/chunkstore/hdb-8708970613374839576/hashstore-sdfs/0/000012.sst: No such file or directory
Can't access /000007.sst: IO error: while stat a file for size: /media/500GB-BKUP/sdfs-volumes/chunkstore/hdb-8708970613374839576/hashstore-sdfs/0/000007.sst: No such file or directory

	at org.rocksdb.RocksDB.open(Native Method)
	at org.rocksdb.RocksDB.open(RocksDB.java:231)
	at org.opendedup.collections.RocksDBMap$StartShard.run(RocksDBMap.java:906)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Service exit with a return value of 255

The three sst files it refers to are definitely not there.  I've attached the logs from the log folder.

The issue occurred on 2 May.  The PC froze around 02h16, and was hard reset around 02h27.  The patches were installed after downloading - from about 02h50 onwards, with the reboot after the patches around 03h02.

What do I do to recover this opendedup instance that will not mount?
[dnf-updates.log](https://github.com/opendedup/sdfs/files/1965901/dnf-updates.log)
[sdfslogs.tar.gz](https://github.com/opendedup/sdfs/files/1965902/sdfslogs.tar.gz)

**Comment by baliramaswamy** [comment]
HI, I have a similar issue

`Can't access /000954.sst: IO error: while stat a file for size: /var/lib/dremio/db/catalog/000954.sst: No such file or directory
Jan 16 15:21:39 ha21t51do dremio: at org.rocksdb.RocksDB.open(Native Method) ~[rocksdbjni-5.14.2.jar:na]
Jan 16 15:21:39 ha21t51do dremio: at org.rocksdb.RocksDB.open(RocksDB.java:286) ~[rocksdbjni-5.14.2.jar:na]
Jan 16 15:21:39 ha21t51do dremio: at com.dremio.datastore.ByteStoreManager.openDB(ByteStoreManager.java:222) ~dremio-services-datastore-3.0.1-201811132128360291-804fe82.jar:3.0.1-201811132128360291-804fe82]
Jan 16 15:21:39 ha21t51do dremio: at com.dremio.datastore.ByteStoreManager.start(ByteStoreManager.java:172) ~[dremio-services-datastore-3.0.1-201811132128360291-804fe82.jar:3.0.1-201811132128360291-804fe82]
Jan 16 15:21:39 ha21t51do dremio: at com.dremio.datastore.CoreStoreProviderImpl.start(CoreStoreProviderImpl.java:195) ~[dremio-services-datastore-3.0.1-201811132128360291-804fe82.jar:3.0.1-201811132128360291-804fe82]
Jan 16 15:21:39 ha21t51do dremio: at com.dremio.datastore.LocalKVStoreProvider.start(LocalKVStoreProvider.java:107) ~[dremio-services-datastore-3.0.1-201811132128360291-804fe82.jar:3.0.1-201811132128360291-804fe82]
Jan 16 15:21:39 ha21t51do dremio: at com.dremio.dac.cmd.upgrade.Upgrade.run(Upgrade.java:177) ~[dremio-dac-daemon-3.0.1-201811132128360291-804fe82.jar:3.0.1-201811132128360291-804fe82]
Jan 16 15:21:39 ha21t51do dremio: at com.dremio.dac.daemon.DremioDaemon.main(DremioDaemon.java:104) ~[dremio-dac-daemon-3.0.1-201811132128360291-804fe82.jar:3.0.1-201811132128360291-804fe82]
`

**Comment by richman1000000** [comment]
you DB is dead.
you can try and run fsck on underlying FS but there is little  chance of success .

I had similar problem and here is tips to prevent it

this triggers flush to disk earlier 
>/etc/sysctl.conf
>vm.dirty_background_bytes = 2097152

use **XFS.** instead of ext4. ext4  have a several warnings after sometime under SDFS directory saying that some index should be shortened .
(/boot and / is still ext4)
>UUID=546d6ac0-68d4-4cde-9b50-ab2854670f85   /media/xfs    xfs   discard,nolargeio,logbufs=8,defaults   0  2

mount dedup storage with **direct_io** option.
> vdedup2tb2  /media/vdedup2tb sdfs       direct_io,noauto 0 0

for XFS user RAID device.

and most important **NEVER USE RESET BUTTON.**

Instead use services for start and stop
[sdfs.service.zip](https://github.com/opendedup/sdfs/files/2778860/sdfs.service.zip)
