### ISSUE TITLE
Can't crate txt or excel or world or ppt file in sdfs

### ISSUE THREAD

**Issue by hukeowen** [opendedup/sdfs#77]
I download the code for sdfs,and run it,it work well.but I Can't crate txt or excel or world or ppt file in sdfs，there is something wrong,0x8000FFFF  
![image](https://user-images.githubusercontent.com/39761936/41264546-d75724da-6e1f-11e8-882d-513f819e4c94.png)。

**Comment by richman1000000** [comment]
run sdfscli --port=6444 --password admin --debug-info on your dedup server
