### ISSUE TITLE
Wrong saved files, when open "No data"

### ISSUE THREAD

**Issue by MgrAlkoholik** [opendedup/sdfs#87]
Hello, what i am doing wrong?

back@Backup:~$ su
Hasło:
root@Backup:/home/back# mount.sdfs b1 /SMB/
Running Program SDFS Version 3.7.7.7 build date 2018-08-08 02:33
reading config file = /etc/sdfs/b1-volume-cfg.xml
multiplier=32 size=8
mem=2105152 memperDB=263144 bufferSize=1073741824 bufferSizePerDB=134217728
Loading Existing Hash Tables |]                                                 
Loading Existing Hash Tables |)))))]                                            
Loading Existing Hash Tables |)))))))))))]                                      
Loading Existing Hash Tables |))))))))))))))))]                                 
Loading Existing Hash Tables |))))))))))))))))))))))]                           
Loading Existing Hash Tables |)))))))))))))))))))))))))))))))))]                
Loading Existing Hash Tables |)))))))))))))))))))))))))))]                      
Loading Existing Hash Tables |))))))))))))))))))))))))))))))))))))))]           
Loading Existing Hash Tables |))))))))))))))))))))))))))))))))))))))))))))]     
Loading Existing Hash Tables |))))))))))))))))))))))))))))))))))))))))))))))))))| 100%

Mounted Filesystem
root@Backup:/home/back# cd /SMB/
root@Backup:/SMB# ls
root@Backup:/SMB# echo jajko >> asd.txt
root@Backup:/SMB# ls
asd.txt
root@Backup:/SMB# cat asd.txt
cat: asd.txt: Brak danych
root@Backup:/SMB# md5sum /etc/sdfs/b1-volume-cfg.xml
a6e04728d8add813561ab54262646796  /etc/sdfs/b1-volume-cfg.xml
root@Backup:/SMB# cp /etc/sdfs/b1-volume-cfg.xml /SMB/
root@Backup:/SMB# md5sum b1-volume-cfg.xml
md5sum: b1-volume-cfg.xml: Brak danych
root@Backup:/SMB#

**Comment by richman1000000** [comment]
Hello!
here is my mount options. 

> vdedup2tb  /media/vdedup2tb sdfs       direct_io,noauto,defaults 0 0

Also not all versions working. This version I'm using. It still have bug with NFS files

> Running SDFS Version 3.7.6.0
