### ISSUE TITLE
Windows installer removed all system PATH variables

### ISSUE THREAD

**Issue by novacrazy** [opendedup/sdfs#90]
A few days ago I installed SDFS with the intention of trying it out sometime soon, and did not restart after installation.

Then, a short while ago, I learned that a new powershell terminal wasn't finding `git`, which was odd.

I checked my `%PATH%` variable only to discover it was totally empty with the exception of `C:\Program Files\sdfs`. Not even the built-in `%SystemRoot%` entries existed anymore.

Luckily I was able to open `cmd.exe` manually and the fact that refreshing environmental variables in Windows is a PITA became my savior and I was able to recover everything. I don't even know if Windows can boot properly without a path variable, so if I had chosen to restart after installation it could have caused serious issues.

OS is Microsoft Windows 10 Pro for Workstations Version 10.0.17134 Build 17134.

Per-user PATH values were unaffected, only system PATH values.

**Comment by novacrazy** [comment]
According to https://nsis.sourceforge.io/Environmental_Variables:_append,_prepend,_and_remove_entries 

"Warning this code will replace paths rather than append if the existing path exceeds the maximum string length in the NSIS build you are using."

My PATH is 472 characters long as of writing this. Although it says the default max length is 1024, but it could be a starting place.

**Comment by qzo** [comment]
Happened to me too. My system path length was 1158 characters. Very annoying, I had to restore the old value from backup.

**Comment by filippobottega** [comment]
Happened to me too. Really poor setup.
