### ISSUE TITLE
.iso fails to install on our proxmox hypervisor 

### ISSUE THREAD

**Issue by greavette** [opendedup/sdfs#91]
Hello Support,

I've downloaded the .iso file from the opendedup website to install Opendedup on my Proxmox virtual hypervisor.  The install works for quite a while but when installing apps it fails for no apparent reason.  I've tried to install on many of the proxmox servers in our cluster and have asked a friend who also run proxmox and both of us have an issue at the same point of the install.  

I'm hoping support can provide some tips I can use to find a reason for the failure.  I will post what's necessary to help debug this issue.

Thank you in advance for any help you can provide me.

**Comment by greavette** [comment]
Hello Support,

Is there anything I can provide for you from my install that would help/assist in finding the root cause of this failure.  The failure message during the install is generic and just says the install failed with the following error message:

Installation step failed:
An installation step failed.  You can try to run the failing items again from the menu, or skip it and choose something else.  The failing step is:  Select and install software

Please assist with getting me past this error.

Thank you.

**Comment by richman1000000** [comment]
hello.
Can you check iso integrity?

**Comment by greavette** [comment]
Yes, myself and my coworker both confirmed the integrity of the .iso we downloaded.  For some reason it just won't install as a VM for us?  

Any ideas what we can do to fix this.  

Thank you.

**Comment by richman1000000** [comment]
From my point of view Owner of OpenDedup trying to sell it. You can buy Enterprise support from website http://polarkey.com.
But the OpenDedup still have several issues and cannot be compared to Data Domain DD6300.

**Comment by richman1000000** [comment]
@greavette  I had the same issue!
You need active internet connection during installation. I used DHCP.
