### ISSUE TITLE
Virtual Appliance Won't Import

### ISSUE THREAD

**Issue by amslife** [opendedup/sdfs#97]
Have tried importing the Datish virtual appliance on both vSphere5.5 and Workstation15, throws errors and doesn't import.

vSphere:
xsi is an undeclared named space line 124 position 11

Workstation:
Failed to open virtual machine: Line 124: Missing attribute 'type' on element 'Section'.
Line 124: Unsupported section 'Section' (Licensing agreement).

**Comment by cliveflint** [comment]
I've just downloaded the .ova file and it's still broken. Not great support. Let's see what else is out there.

**Comment by richman1000000** [comment]
you can open ova file with 7zip or other archive app and extract disk image
